default_to_none = true
id = "kAJcI 65 jagadguru zrI~sudarzana mahAdEvEndra sarasvatI ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = "मध्यार्जुनमहालिङ्गनामा हारीतगोत्रजः।\nशेषाद्रिशास्त्रिणः सुब्बुलक्ष्म्यां पत्न्यां व्यजायत॥१६॥\nउपषष्टे स्ववयसि विश्रमग्रामम् आगतः।\nशिवालयान्तिके तत्र शैवं भावम् उपागमत्॥१७॥\nपीठे महादेवेन्द्राख्यस्त्रिंशन्नव समाः स्थितः।\nविरोधिफाल्गुनामायां गुरुः कैवल्यम् आस्थितः॥१८॥\n—पुण्यश्लोकमञ्जरी"
image = "kAnchI-maTha/images/jagadgurus/jagadguru-65.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 12
anga_type = "tithi"
anga_number = 30
kaala = "अपराह्णः"
year_start = 4991
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Preceptor Mahādevendra adorned the Pīṭha for thirty-nine years and attaind Siddhi on the new moon day in the month of Phālguṇa of the year Virodhi. This preceptor’s name before initiation was Mahāliṅgam. His parents were well-known as Lakṣmī and Śeṣādri. His place of siddhi was a village called Ilayāttaṅguḍi. Śalivahana era 1813."

[names]
sa = [ "काञ्ची ६५ जगद्गुरु श्री-सुदर्शन महादेवेन्द्र सरस्वती आराधना",]
