default_to_none = true
id = "kAJcI 13 jagadguru zrI~saccidghanEndra sarasvatI ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = "सप्तत्रिंशद् असौ समाः समनुभूयाचार्यपीठीधुरां\nश्रीविद्याघनम् आन्ध्रवर्णिनम् अधाच्छ्रीनायनाख्यं मठे।\nभ्राम्यन् बालवद् अन्तरे पुरवरस्याऽऽधूतवृत्तिः स्थिरः\nश्रीसच्चिद्घनदेशिकः समभजत् स्वान्तर्धिम् अन्वीश्वरम्॥२५॥\nसूनुः श्रीधरपण्डितस्य गरुडस्रोतस्विनीतीरभूः\nशेषाख्यो गुरुचन्द्रशेखरमुनेः शिष्यश्च सच्चिद्घनः।\nवर्षान् सप्ततिम् एकवर्जम् अनुभूयाध्यात्मबुद्ध्या सुखं\nदेहान्ते शिवलिङ्गमध्यम् अविशत् कायाधिरोहेशितुः॥२६॥\nखरेऽखरप्रकृतिरघासहः सहे परोरजाः परम् अपरे च पक्षके।\nअधाद् अधिप्रतिपद् अनापदास्पदं परात्परं पदम् अशरीरम् अव्ययम्॥२७॥\n—पुण्यश्लोकमञ्जरी"
image = "kAnchI-maTha/images/jagadgurus/jagadguru-13.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 9
anga_type = "tithi"
anga_number = 16
kaala = "अपराह्णः"
year_start = 3373
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Then, the preceptor Śrī Cidghana, having governed or held the responsibilities of Ācārya Pīṭha for thirtyseven years, placed his disciple Śrī Vidyāghana, who was known as Śrī Nāyana in Pūrvāśrama before initiation, in the Maṭha; adhering to ascetic principles, wandering like a child, He vanished in the divine form of Ăśvara. Śrī Sacchidānanda, named Śeṣa (before initiation), son of Śrīdhrapaṇḍita, born on the banks of river Garuḍa, disciple of Preceptor Chandraśekahara having enjoyed the bliss through spiritual practices for sixty-nine years, and at the end of life entered into the Śivaliṅga—Kāyādhirohaneśvara. The great preceptor, the transcendental, immaculate attained the supreme state devoid of pains, beyond everything, imperishable and infinite on the first day of the dark fortnight in the month of Mārgaśīrṣa in the year Khara. "

[names]
sa = [ "काञ्ची १३ जगद्गुरु श्री-सच्चिद्घनेन्द्र सरस्वती आराधना",]
