default_to_none = true
id = "kAJcI 25 jagadguru zrI~saccidAnandaghanEndra sarasvatI ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = "श्रीमुष्णकृष्णतनयः शिवसाम्बनामा यस्त्रिः प्रदक्षिणितपुण्यमहिर्महात्मा।\nश्रीचित्सुखेन्द्रयमिनः श्रितशिष्यभावः श्रीशारदामठविभुः समभूत् स शान्तः॥५२॥\nयदीयवृत्तं निबबन्ध मन्थो निबन्धने सिद्धजयाभिधाने।\nस विंशतिं सैकसमाः स्वपीठे निषद्य नित्यत्वम् अवाप सद्यः॥५३॥\nअधिसप्ततिके चतुश्शिरस्के (४७०) सच्चिदानन्दघनः स सन् शकाब्दे।\nप्रभवे प्रभवन् शुचिश्च शुच्योः प्रथमायां पृथुलिङ्गताम् अवापत्॥५४॥\n—पुण्यश्लोकमञ्जरी"
image = "kAnchI-maTha/images/jagadgurus/jagadguru-25.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 4
anga_type = "tithi"
anga_number = 1
kaala = "अपराह्णः"
year_start = 3649
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "The noble son of Śrīkṛṣṇa of Śrīmuṣṇa by name Śivasāmbha who went round the earth thrice, became a disciple of Śrīcitrukha through initiation, and later became the head of Śrī Śārada maṭha. He (Śrī Citsukhendra), whose biography was composed by Mantha in his work titled Siddhajaya adorned the Pīṭha for twenty-one years and attained immortal state. He, the austere, Saccidānandaghana attained immortality in the form of Śivaliṅga on the first day of the bright fortnight in the month of Āṣāḍha of Prabhava year in the Śaka era 470."

[names]
sa = [ "काञ्ची २५ जगद्गुरु श्री-सच्चिदानन्दघनेन्द्र सरस्वती आराधना",]
