default_to_none = true
id = "kAJcI 49 jagadguru zrI~mahAdEvEndra sarasvatI 3 ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = "छायावनाच्युतसुतो गुरुमूर्तिनामा स्थित्वा जगद्गुरुपदे छवि(४७)वर्षकालम्।\nप्राप्तोऽपराभवपदं स पराभवोर्जकालाष्टमीनिशि पदं परमात्मसंज्ञम्॥९६॥\n—पुण्यश्लोकमञ्जरी"
image = "kAnchI-maTha/images/jagadgurus/jagadguru-49.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 8
anga_type = "tithi"
anga_number = 23
kaala = "अपराह्णः"
year_start = 4348
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Son of Chāyāvana Acyuta, He was Gurumūrthi by name (before initiation); having adorned the seat of Jagadguru for forty-seven years, He attained on the night of Kālāṣṭamī of the month Kārtika in the year Parābhava—the Supreme state denoted by the term Paramātman."

[names]
sa = [ "काञ्ची ४९ जगद्गुरु श्री-महादेवेन्द्र सरस्वती ३ आराधना",]
