default_to_none = true
id = "kAJcI 58 jagadguru zrI~AtmabOdhEndra sarasvatI ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = "वृद्धाचलप्रभवविश्वमखीन्द्रसूनुर्विश्वेश्वरः परशिवार्यपदं प्रपन्नः।\nआसेतुशीतगिरि कल्पितजैत्रयात्र आद्यात् स शङ्करगुरोरतिहृद्य आसीत्॥६॥\nविश्वाधिकस्वधिषणत्वत एनमाहुर्विश्वाधिकेन्द्रम् अनघा नवशङ्करं च।\nश्रीरुद्रभाष्यमुखभूरितरप्रबन्धसन्धानकौशलम् अमुष्य किमप्यमेयम्॥७॥\nद्वापञ्चाशतम् उद्वहन् गुरुधुराम् अब्दानवाच्यां दिशि प्रस्थाने गरुडापगातटभुवि प्रापत् पदं शाश्वतम्।\nबोधेन्द्रार्यविसृष्टविष्टरधुरो विश्वाधिकेन्द्रस्तुलाकृष्णाष्टम्यहनीश्वरे हृदि दधत् सोमार्धचूडामणिम्॥८॥\n—पुण्यश्लोकमञ्जरी"
image = "kAnchI-maTha/images/jagadgurus/jagadguru-58.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 8
anga_type = "tithi"
anga_number = 23
kaala = "अपराह्णः"
year_start = 4739
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Viśveśvara was the son of Viśvamakhindra; resorting to the fact of Paraśivārya, known as Navaśaṅkara from the first preceptor toured all places successfully, from Setu (Rāmeśvaram) to Sītāgiri (Himalayas). Since He possessed intellect more than anyone in the Universe, men of wisdom call him Viśvādhika and Navaśaṅkara. His erudition in composing works such as Rudra bhāṣya is beyond words—immeasurable. The preceptor Viśvādhikendra carrying out the responsibilities of preceptor for fifty-two years, (later) handing over the responsibilities to Bodhendrārya, and proceeding in southern direction reached eternal abode, meditating on Lord Śiva with the crescent moon in the crown, on the banks of river Garuḍa on the eighth day of the black fortnight in the month of Tulā of the year Ăśvara. This preceptor Śrī Navaśaṅkara residing on the banks of river Tridaśa was revered by eminent men, departed in the southern direction and attained siddhi on the banks of river Garuḍa after handing over the responsibilities to the disciple Śrī Bhagavannāma Bodhendra. "

[names]
sa = [ "काञ्ची ५८ जगद्गुरु श्री-आत्मबोधेन्द्र सरस्वती आराधना",]
