default_to_none = true
id = "kAJcI 33 jagadguru zrI~saccidAnandaghanEndra sarasvatI 2 ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = "नानाभाषाभिलापी प्रशमकुलधनः प्रौढरामण्णसूनुः\nत्रैलिङ्गस्तिम्मणाख्यो भुवनगुरुरभूच्चन्द्रभागाप्रतीरात्।\nकाञ्च्यामेवाधिपीठं मठमपि विपुलं जीर्णमुद्धृत्य नित्यं\nकामाक्ष्यर्चैकनिष्ठः सुखम् अवसदसौ सच्चिदानन्दसान्द्रः॥६४॥\nखरे प्रौष्ठपदे षष्ठ्याम् अखरोऽधिमहालयम्।\nस सच्चिदानन्दघनो महान् लयमगाद् गुरुः॥६५॥\n—पुण्यश्लोकमञ्जरी"
image = "kAnchI-maTha/images/jagadgurus/jagadguru-33.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 6
anga_type = "tithi"
anga_number = 21
kaala = "अपराह्णः"
year_start = 3793
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "This Saccidānandaghana with a firm control over senses, conversant with various languages—was a Telugu brahmin named Timmaṇṇa, son of Prauḍha Rāmaṇṇa became the Jagadguru from region on the banks of river Chandrabhāga. Renovating the huge dilapidated maṭha, He remained happily in Kāñci itself by devoting himself every day in the worship of Goddess Kāmākṣī. He, the benevolent great preceptor Saccidānandaghana having travelled upto Himalayas attained liberation on the eighth day of bright fortnight of the month Bhādrapada in the year Khara. He was also known as Bhāṣaparameṣṭi and his preceptorship was for twenty years."

[names]
sa = [ "काञ्ची ३३ जगद्गुरु श्री-सच्चिदानन्दघनेन्द्र सरस्वती २ आराधना",]
