default_to_none = true
id = "vidyAraNya-svAmI~jayantI"
tags = [ "MahapurushaEvents",]
references_secondary = [ "http://hindupad.com/vidyaranya-jayanti-swami-vidyaranya-jayanthi/",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 2
anga_type = "tithi"
anga_number = 7
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "विद्यारण्य-स्वामि-जयन्ती",]
