default_to_none = true
id = "kAJcI 55 jagadguru zrI~candracUDEndra sarasvatI 3 ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = "मधुरितमणिमुक्तामुग्धतीराश्मशालापुरतिलकपुरारिश्रीमतीपुण्यपुञ्जम्।\nअरुणगिरिरभार्षीद् अद्वयाचार्यमुद्रां चतुरुदधिपटायां चन्द्रचूडेन्द्रनामा॥१०८॥\nइत्थं मामनुशिष्य शिष्यकणिशं तांस्तान् समस्तांस्ततः\nसन्दर्श्य क्षणतः स सिद्धिमसदद् वर्षान् षडेव स्थितः।\nकाञ्च्यामाङ्गिरसे सहस्यधवलैकादश्यहे प्रत्युष-\nस्यापत् सिद्धिमनापदि प्रतिपदं सच्चित्सुखे ज्योतिषि॥१०९॥\n-\n—पुण्यश्लोकमञ्जरी"
image = "kAnchI-maTha/images/jagadgurus/jagadguru-55.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 10
anga_type = "tithi"
anga_number = 11
kaala = "अपराह्णः"
year_start = 4625
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Heaps of merits embodied as the son of Purāri and Śrīmati of the town Aśmaśālapura on the banks of the sweet river Maṇimukta, Aruṇagiri governed the preceptorship of the Pīṭha surrounded by the four oceans as preceptor candracūḍa. Sri Kṛṣṇapremi’s edition Thus having imparted the teachings to me, the insignificant disciple and guiding me through various aspects pertaining to the Pīṭha, the preceptor who remained in the Pīṭha for sixteen years and attained siddhi in a moment, He merged in theSupreme Effulgence (of the nature) Saccitsukha devoid of calamities, on the eleventh day of the bright fortnight early morning of the month of Mīna of the year Svabhānu at Kañci. Polakam Rāmaśāstri edition Thus having imparted the teachings to me, the insignificant among disciples and guiding me through all aspects relating to the Pīṭha, the preceptor who stayed at the Maṭha for only six years at siddhi in a moment, He merged in the Eternal Bliss, the Supreme Effulgence, devoid of calamities at the dawn of eleventh day of bright fortnight of the Mārgaśīrṣa month in the year Āṅgīrasa at Kañci. "

[names]
sa = [ "काञ्ची ५५ जगद्गुरु श्री-चन्द्रचूडेन्द्र सरस्वती ३ आराधना",]
