default_to_none = true
id = "zaGkara~jayantI"
tags = [ "CommonFestivals", "AdiShankaraHistory", "MahapurushaEvents",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "paraviddha"
month_number = 2
anga_type = "tithi"
anga_number = 5
kaala = "प्रातः"
year_start = 2593
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Nandana year"

[names]
sa = [ "शङ्कर-जयन्ती",]
