default_to_none = true
id = "zRGgErI zAradAmaTha-pratiSThApana~jayantI"
tags = [ "AdiShankaraHistory",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 10
anga_type = "tithi"
anga_number = 15
year_start = 2618
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Adi Shankara founded Sharada Mutt, Shringeri in Pingala year Sureshwaracharya as first"

[names]
sa = [ "शृङ्गेरी शारदामठ-प्रतिष्ठापन-जयन्ती",]
